# this is the file used to deploy on Portainer
# or other more permanent hosting solutions
version: "3.7"

services:
  myapp:
    container_name: myapp
    image: dockerstepbystep:testing1
    build: .
    ports:
      - "8080:8080"
    volumes:
      - "app_data:/var/app_data"

volumes:
  app_data:
  
